# Generated by Django 5.2 on 2025-08-03 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_yourmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='auter',
            new_name='author',
        ),
    ]
